---
title: "Values"
about:
  id: hero-heading
  template: marquee
---

::: {#hero-heading}
*"The relationship between teacher and student is...different from what it was in the past. The former is no longer there for the sake of the latter; both are there for the sake of Wissenschaft \[Science\]"*

--Wilhelm von Humboldt

### Classroom Values:

Whether we are studying Anatomy and Physiology, Evolution, or Bioinformatics, we will be addressing a wide range of important questions. Examining such challenging questions is sometimes difficult, but it becomes easier when we work together. I strongly believe students and teachers can most effectively engage with science in an environment where all students bring 100% of themselves to the classroom: their identities, values, motivations, goals, and experiences. In the pursuit of creating a space where this can be achieved, the following values[^1] inspire the classroom I hope to create:

*Humanity:* We approach science as complete individuals with a range of experiences and perspectives. When we enter a classroom, we enter as the product of our lived experiences, communities, values, and identity. These experiences are valued by all members of our classroom community.

*Humility:* By its nature, science is rooted in the appreciation of what we don't know. None of us are perfect, and the classroom is a space where we can make mistakes. On my end, I will do my best to meet my students where they are, provide the help I can give, and demonstrate patience. On your end, I would like you to feel empowered to support each other, and ask for help when needed.

*Communication:* Teaching is rooted in communication and dialogue. I have found, both as a learner and a teacher, that by talking about lecture material with a friend or putting it in writing, the challenge becomes easier. This is why we have classrooms: to communicate! I will be as communicative as possible as a lecturer, but for our classroom to succeed, you also need to communicate. Answer questions, ask questions, and come to office hours to work through your understanding of the topics.

### On Grading:

Reducing a person's accomplishments and knowledge to a letter grade cannot capture their experiences in a classroom. However, I also am providing a service to Stonehill College and the scientific community as a whole, and part of that service is giving you a letter grade. I ask that you respect the grading structure given in the syllabus. In return, I intend to approach grading in the spirit of humility, and am happy to have open dialogue on how to most effectively grade.

### On AI:

In my opinion, the resources provided by AI tools such as ChatGPT, while useful, run against the values of my classroom (as AI models do not approach learning in the spirit of humanity, humility, or communication). Please do not use AI tools as teachers or "Cliffsnotes". It may make your problem "feel" easier, but it won't lead to lasting knowledge. Please respect the AI policy of any given class. If you believe the tools provided by an AI resource will help you more effectively engage with an assignment or the classroom, contact me and we will talk.
:::

[^1]: This approach to community building has been inspired by (and in some places, paraphrased) the work of Daniela Palmer and Yan Wang (in their case with the aim of developing a lab culture). My perspective on education has been shaped by a wide variety of educators throughout the years, but most directly by the mentorship of Marion Alberty and the writing of Agnes Callard.
